/**
 * Global Styles
 * Centralized styling for the main App component
 */

import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#1C1C1E',
  },
  backgroundImage: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  backgroundImageStyle: {
    opacity: 0.15,
  },
  headerContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '85%',
    marginBottom: 16,
  },
  scoreContainer: {
    flexDirection: 'row',
    alignItems: 'baseline',
    gap: 8,
  },
  stockContainer: {
    alignItems: 'center',
  },
  stockText: {
    fontSize: 18,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.35)',
  },
  stockLabel: {
    fontSize: 8,
    color: 'rgba(255, 255, 255, 0.2)',
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  scoreText: {
    fontSize: 24,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  comboText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#E8943A',
  },
  gridContainer: {
    width: '96%',
    alignItems: 'center',
  },
  grid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
    aspectRatio: 1,
    // No padding here - cells handle their own spacing with internal padding
    // This prevents percentage width calculation issues on large screens
    backgroundColor: '#1A1A1C',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#2A2A2E',
    position: 'relative',
    alignContent: 'flex-start',
    justifyContent: 'flex-start',
    overflow: 'hidden',
  },
  connectionsContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  menuButton: {
    position: 'absolute',
    top: 50,
    left: 16,
    paddingVertical: 8,
    paddingHorizontal: 12,
    zIndex: 10,
  },
  menuButtonText: {
    fontSize: 14,
    fontWeight: '500',
    color: 'rgba(255, 255, 255, 0.5)',
  },
  shuffleButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(100, 160, 180, 0.3)',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(100, 160, 180, 0.5)',
    gap: 4,
  },
  shuffleButtonDisabled: {
    backgroundColor: 'rgba(80, 80, 80, 0.2)',
    borderColor: 'rgba(80, 80, 80, 0.3)',
  },
  shuffleButtonActive: {
    backgroundColor: 'rgba(100, 200, 180, 0.4)',
    borderColor: 'rgba(100, 200, 180, 0.6)',
  },
  shuffleButtonUrgent: {
    backgroundColor: 'rgba(255, 150, 100, 0.5)',
    borderColor: 'rgba(255, 150, 100, 0.8)',
    borderWidth: 2,
  },
  shuffleIcon: {
    fontSize: 16,
  },
  shuffleCount: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.7)',
  },
  freeModeHeader: {
    alignItems: 'center',
    marginBottom: 8,
  },
  freeModeTitleText: {
    fontSize: 18,
    fontWeight: '700',
    color: 'rgba(100, 160, 180, 0.9)',
    fontFamily: 'monospace',
    letterSpacing: 2,
  },
  freeModeHighScoreText: {
    fontSize: 12,
    fontWeight: '400',
    color: 'rgba(255, 215, 0, 0.8)',
    fontFamily: 'monospace',
    marginTop: 2,
  },
  tutorialHintContainer: {
    alignItems: 'center',
    marginBottom: 8,
  },
  tutorialHintText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFD700',
    textAlign: 'center',
    textShadowColor: 'rgba(255, 215, 0, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  // Power-ups container (Free Mode)
  powerUpsContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 16,
    marginBottom: 8,
    gap: 20,
  },
  powerUpWrapper: {
    alignItems: 'center',
  },
  powerUpHint: {
    fontSize: 14,
    fontWeight: '600',
    color: '#00FFFF',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 255, 255, 0.5)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 8,
    marginBottom: 8,
  },
  // Short Circuit styles
  shortCircuitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 200, 255, 0.2)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(0, 255, 255, 0.5)',
    gap: 8,
  },
  shortCircuitButtonDisabled: {
    backgroundColor: 'rgba(80, 80, 80, 0.2)',
    borderColor: 'rgba(80, 80, 80, 0.3)',
  },
  shortCircuitButtonActive: {
    backgroundColor: 'rgba(0, 255, 255, 0.4)',
    borderColor: '#00FFFF',
    shadowColor: '#00FFFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  shortCircuitIcon: {
    width: 40,
    height: 40,
  },
  shortCircuitCount: {
    fontSize: 16,
    fontWeight: '700',
    color: 'rgba(255, 255, 255, 0.9)',
    fontFamily: 'monospace',
  },
  // Reprogram styles
  reprogramButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 150, 0, 0.2)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 180, 0, 0.5)',
    gap: 8,
  },
  reprogramButtonDisabled: {
    backgroundColor: 'rgba(80, 80, 80, 0.2)',
    borderColor: 'rgba(80, 80, 80, 0.3)',
  },
  reprogramButtonActive: {
    backgroundColor: 'rgba(255, 180, 0, 0.4)',
    borderColor: '#FFB400',
    shadowColor: '#FFB400',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 10,
  },
  reprogramIcon: {
    width: 40,
    height: 40,
  },
  reprogramCount: {
    fontSize: 16,
    fontWeight: '700',
    color: 'rgba(255, 255, 255, 0.9)',
    fontFamily: 'monospace',
  },
  // Reprogram modal styles
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 100,
  },
  reprogramModal: {
    backgroundColor: 'rgba(15, 35, 50, 0.98)',
    borderRadius: 20,
    padding: 28,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(0, 200, 255, 0.6)',
    minWidth: 300,
    shadowColor: '#00CCFF',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 15,
  },
  reprogramModalTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#00DDFF',
    marginBottom: 8,
    textShadowColor: 'rgba(0, 200, 255, 0.6)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 10,
  },
  reprogramModalSubtitle: {
    fontSize: 14,
    color: 'rgba(200, 230, 255, 0.8)',
    marginBottom: 24,
  },
  reprogramValueGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    gap: 14,
    marginBottom: 24,
  },
  reprogramValueButton: {
    width: 54,
    height: 54,
    borderRadius: 12,
    backgroundColor: 'transparent',
    borderWidth: 2,
    borderColor: 'rgba(0, 200, 255, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  reprogramValueText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 200, 255, 0.4)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  reprogramCancelButton: {
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(100, 150, 180, 0.4)',
  },
  reprogramCancelText: {
    fontSize: 14,
    color: 'rgba(150, 180, 200, 0.8)',
  },
});

export default styles;
